//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveStoryModdingFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaveStoryModdingFramework.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance from the center of the NPC to the back of its hitbox (changes based on direction the NPC is facing).
        /// </summary>
        internal static string BackDescription {
            get {
                return ResourceManager.GetString("BackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What flags this entity has set.
        /// </summary>
        internal static string BitsDescription {
            get {
                return ResourceManager.GetString("BitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance from the center of the NPC to the bottom of its hitbox.
        /// </summary>
        internal static string BottomDescription {
            get {
                return ResourceManager.GetString("BottomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What event is assosciated with this entity.
        /// </summary>
        internal static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What flag is associsated with this entity.
        /// </summary>
        internal static string FlagDescription {
            get {
                return ResourceManager.GetString("FlagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Layout.
        /// </summary>
        internal static string FoldersCategory {
            get {
                return ResourceManager.GetString("FoldersCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance from the center of the NPC to the front of its hitbox (changes based on direction the NPC is facing).
        /// </summary>
        internal static string FrontDescription {
            get {
                return ResourceManager.GetString("FrontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay.
        /// </summary>
        internal static string GameplayCategory {
            get {
                return ResourceManager.GetString("GameplayCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string ImagesCategory {
            get {
                return ResourceManager.GetString("ImagesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How far to offset the NPC horizontally, when it faces left.
        /// </summary>
        internal static string LeftOffsetDescription {
            get {
                return ResourceManager.GetString("LeftOffsetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filenames.
        /// </summary>
        internal static string ModFilenameCategory {
            get {
                return ResourceManager.GetString("ModFilenameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Table.
        /// </summary>
        internal static string ModStageTableCategory {
            get {
                return ResourceManager.GetString("ModStageTableCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSC.
        /// </summary>
        internal static string ModTSCOptions {
            get {
                return ResourceManager.GetString("ModTSCOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Table.
        /// </summary>
        internal static string NPCTable {
            get {
                return ResourceManager.GetString("NPCTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How far to offset the NPC horizontally, when it faces any direction other than left.
        /// </summary>
        internal static string RightOffsetDescription {
            get {
                return ResourceManager.GetString("RightOffsetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        internal static string TilesCategory {
            get {
                return ResourceManager.GetString("TilesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance from the center of the NPC to the top of its hitbox.
        /// </summary>
        internal static string TopDescription {
            get {
                return ResourceManager.GetString("TopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of eneitity this is.
        /// </summary>
        internal static string TypeDescription {
            get {
                return ResourceManager.GetString("TypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unused value stored in the NPC table.
        /// </summary>
        internal static string UnusedDescription {
            get {
                return ResourceManager.GetString("UnusedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X position of the entity.
        /// </summary>
        internal static string XDescription {
            get {
                return ResourceManager.GetString("XDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y position of the entity.
        /// </summary>
        internal static string YDescription {
            get {
                return ResourceManager.GetString("YDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How far to offset the NPC vertically.
        /// </summary>
        internal static string YOffsetDescription {
            get {
                return ResourceManager.GetString("YOffsetDescription", resourceCulture);
            }
        }
    }
}
