//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveStoryModdingFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SurfaceNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SurfaceNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaveStoryModdingFramework.SurfaceNames", typeof(SurfaceNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arms.pbm.
        /// </summary>
        internal static string Arms {
            get {
                return ResourceManager.GetString("Arms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmsImage.pbm.
        /// </summary>
        internal static string ArmsImage {
            get {
                return ResourceManager.GetString("ArmsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Current Background&gt;.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet.pbm.
        /// </summary>
        internal static string Bullet {
            get {
                return ResourceManager.GetString("Bullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caret.pbm.
        /// </summary>
        internal static string Caret {
            get {
                return ResourceManager.GetString("Caret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casts.pbm.
        /// </summary>
        internal static string Casts {
            get {
                return ResourceManager.GetString("Casts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits Image Buffer.
        /// </summary>
        internal static string CreditsImage {
            get {
                return ResourceManager.GetString("CreditsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits Text Buffer.
        /// </summary>
        internal static string CreditsText {
            get {
                return ResourceManager.GetString("CreditsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Number Buffer.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face.pbm.
        /// </summary>
        internal static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade.pbm.
        /// </summary>
        internal static string Fade {
            get {
                return ResourceManager.GetString("Fade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemImage.pbm.
        /// </summary>
        internal static string ItemImage {
            get {
                return ResourceManager.GetString("ItemImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.pbm.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map System Buffer.
        /// </summary>
        internal static string MapSystem {
            get {
                return ResourceManager.GetString("MapSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        internal static string MAX {
            get {
                return ResourceManager.GetString("MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MNA Buffer.
        /// </summary>
        internal static string MNA {
            get {
                return ResourceManager.GetString("MNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyChar.pbm.
        /// </summary>
        internal static string MyChar {
            get {
                return ResourceManager.GetString("MyChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NpcRegu.pbm.
        /// </summary>
        internal static string NpcRegu {
            get {
                return ResourceManager.GetString("NpcRegu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NpcSym.pbm.
        /// </summary>
        internal static string NpcSym {
            get {
                return ResourceManager.GetString("NpcSym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap/PIXEL (Resource).
        /// </summary>
        internal static string PIXEL {
            get {
                return ResourceManager.GetString("PIXEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Buffer.
        /// </summary>
        internal static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Spritesheet 1&gt;.
        /// </summary>
        internal static string Spritesheet1 {
            get {
                return ResourceManager.GetString("Spritesheet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Spritesheet 2&gt;.
        /// </summary>
        internal static string Spritesheet2 {
            get {
                return ResourceManager.GetString("Spritesheet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StageImage.pbm.
        /// </summary>
        internal static string StageImage {
            get {
                return ResourceManager.GetString("StageImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox.pbm.
        /// </summary>
        internal static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Line 1.
        /// </summary>
        internal static string TextLine1 {
            get {
                return ResourceManager.GetString("TextLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Line 2.
        /// </summary>
        internal static string TextLine2 {
            get {
                return ResourceManager.GetString("TextLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Line 3.
        /// </summary>
        internal static string TextLine3 {
            get {
                return ResourceManager.GetString("TextLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Line 4.
        /// </summary>
        internal static string TextLine4 {
            get {
                return ResourceManager.GetString("TextLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Line 5.
        /// </summary>
        internal static string TextLine5 {
            get {
                return ResourceManager.GetString("TextLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Current Tileset&gt;.
        /// </summary>
        internal static string Tileset {
            get {
                return ResourceManager.GetString("Tileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.pbm.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
