//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveStoryModdingFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TSCCommandDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TSCCommandDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaveStoryModdingFramework.TSCCommandDescriptions", typeof(TSCCommandDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refill all weapon ammo.
        /// </summary>
        internal static string AEPlus {
            get {
                return ResourceManager.GetString("AEPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to event X if the PC has weapon W.
        /// </summary>
        internal static string AMJ {
            get {
                return ResourceManager.GetString("AMJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove weapon W.
        /// </summary>
        internal static string AMMinus {
            get {
                return ResourceManager.GetString("AMMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give weapon W with X ammo. Use 0000 for infinite ammo.
        /// </summary>
        internal static string AMPlus {
            get {
                return ResourceManager.GetString("AMPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give all entities W scriptstate X and direction Y.
        /// </summary>
        internal static string ANP {
            get {
                return ResourceManager.GetString("ANP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give map-boss scriptstate W.
        /// </summary>
        internal static string BOA {
            get {
                return ResourceManager.GetString("BOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start boss fight with entity W. Use 0000 to end the boss fight.
        /// </summary>
        internal static string BSL {
            get {
                return ResourceManager.GetString("BSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantly display text. Use before a &lt;MSG/2/3; works until &lt;END. Same command as &lt;SAT.
        /// </summary>
        internal static string CAT {
            get {
                return ResourceManager.GetString("CAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear illustration (during credits).
        /// </summary>
        internal static string CIL {
            get {
                return ResourceManager.GetString("CIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close message box.
        /// </summary>
        internal static string CLO {
            get {
                return ResourceManager.GetString("CLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear message box..
        /// </summary>
        internal static string CLR {
            get {
                return ResourceManager.GetString("CLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the tile at coordinates W:X to type Y. Produces smoke.
        /// </summary>
        internal static string CMP {
            get {
                return ResourceManager.GetString("CMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change music to song W.
        /// </summary>
        internal static string CMU {
            get {
                return ResourceManager.GetString("CMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change all entities W to type X with direction Y.
        /// </summary>
        internal static string CNP {
            get {
                return ResourceManager.GetString("CNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the propeller sound.
        /// </summary>
        internal static string CPS {
            get {
                return ResourceManager.GetString("CPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolls credits.
        /// </summary>
        internal static string CRE {
            get {
                return ResourceManager.GetString("CRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the stream sound..
        /// </summary>
        internal static string CSS {
            get {
                return ResourceManager.GetString("CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all entities of type W.
        /// </summary>
        internal static string DNA {
            get {
                return ResourceManager.GetString("DNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all entities W.
        /// </summary>
        internal static string DNP {
            get {
                return ResourceManager.GetString("DNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to event X if any entities W exist.
        /// </summary>
        internal static string ECJ {
            get {
                return ResourceManager.GetString("ECJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends the current event.
        /// </summary>
        internal static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dequip item(s) W.
        /// </summary>
        internal static string EQMinus {
            get {
                return ResourceManager.GetString("EQMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip item(s) W.
        /// </summary>
        internal static string EQPlus {
            get {
                return ResourceManager.GetString("EQPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit to title screen.
        /// </summary>
        internal static string ESC {
            get {
                return ResourceManager.GetString("ESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to event W.
        /// </summary>
        internal static string EVE {
            get {
                return ResourceManager.GetString("EVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show face W in the message box.
        /// </summary>
        internal static string FAC {
            get {
                return ResourceManager.GetString("FAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade in with direction W.
        /// </summary>
        internal static string FAI {
            get {
                return ResourceManager.GetString("FAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade out with direction W.
        /// </summary>
        internal static string FAO {
            get {
                return ResourceManager.GetString("FAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash the screen white.
        /// </summary>
        internal static string FLA {
            get {
                return ResourceManager.GetString("FLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to event X if flag W is set.
        /// </summary>
        internal static string FLJ {
            get {
                return ResourceManager.GetString("FLJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset flag W.
        /// </summary>
        internal static string FLMinus {
            get {
                return ResourceManager.GetString("FLMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set flag W. Valid flags range from 0-7999.
        /// </summary>
        internal static string FLPlus {
            get {
                return ResourceManager.GetString("FLPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade the music out.
        /// </summary>
        internal static string FMU {
            get {
                return ResourceManager.GetString("FMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus on boss W in X ticks. Use X &gt; 0.
        /// </summary>
        internal static string FOB {
            get {
                return ResourceManager.GetString("FOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus on the PC in W ticks. Use W &gt; 0.
        /// </summary>
        internal static string FOM {
            get {
                return ResourceManager.GetString("FOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus on entity W in X ticks. Use X &gt; 0.
        /// </summary>
        internal static string FON {
            get {
                return ResourceManager.GetString("FON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free game action and the PC.
        /// </summary>
        internal static string FRE {
            get {
                return ResourceManager.GetString("FRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display an item or weapon icon above the message box. Add 1000 to W for items. Use 0000 to remove.
        /// </summary>
        internal static string GIT {
            get {
                return ResourceManager.GetString("GIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the PC.
        /// </summary>
        internal static string HMC {
            get {
                return ResourceManager.GetString("HMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset memory and restart game.
        /// </summary>
        internal static string INI {
            get {
                return ResourceManager.GetString("INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change entity W to type X with direction Y and set entity flag 100 (0x8000).
        /// </summary>
        internal static string INP {
            get {
                return ResourceManager.GetString("INP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to event X if the PC has item W.
        /// </summary>
        internal static string ITJ {
            get {
                return ResourceManager.GetString("ITJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove item W.
        /// </summary>
        internal static string ITMinus {
            get {
                return ResourceManager.GetString("ITMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give item W.
        /// </summary>
        internal static string ITPlus {
            get {
                return ResourceManager.GetString("ITPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock player controls and hide status bars until &lt;END..
        /// </summary>
        internal static string KEY {
            get {
                return ResourceManager.GetString("KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the saved game.
        /// </summary>
        internal static string LDP {
            get {
                return ResourceManager.GetString("LDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover W health.
        /// </summary>
        internal static string LIPlus {
            get {
                return ResourceManager.GetString("LIPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the map system view of/enters the map loop for the current area.
        /// </summary>
        internal static string MLP {
            get {
                return ResourceManager.GetString("MLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the current and maximum health by W.
        /// </summary>
        internal static string MLPlus {
            get {
                return ResourceManager.GetString("MLPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt the PC&apos;s forward motion.
        /// </summary>
        internal static string MM0 {
            get {
                return ResourceManager.GetString("MM0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the map name.
        /// </summary>
        internal static string MNA {
            get {
                return ResourceManager.GetString("MNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move entity W to coordinates X:Y with direction Z.
        /// </summary>
        internal static string MNP {
            get {
                return ResourceManager.GetString("MNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the PC to coordinates W:X.
        /// </summary>
        internal static string MOV {
            get {
                return ResourceManager.GetString("MOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to event W if the map flag for the current area is set.
        /// </summary>
        internal static string MPJ {
            get {
                return ResourceManager.GetString("MPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set map flag W. Map flags cannot be unset. Highest usable flag is 127..
        /// </summary>
        internal static string MPPlus {
            get {
                return ResourceManager.GetString("MPPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an invisible message box at the top of screen.
        /// </summary>
        internal static string MS2 {
            get {
                return ResourceManager.GetString("MS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a message box at the top of screen.
        /// </summary>
        internal static string MS3 {
            get {
                return ResourceManager.GetString("MS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a message box at the bottom of the screen.
        /// </summary>
        internal static string MSG {
            get {
                return ResourceManager.GetString("MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes the PC to hop in the direction opposite of W. Using up or down causes the jump to be vertical.
        /// </summary>
        internal static string MYB {
            get {
                return ResourceManager.GetString("MYB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes the PC to face direction W.
        /// </summary>
        internal static string MYD {
            get {
                return ResourceManager.GetString("MYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to event X if any entity of type W exists.
        /// </summary>
        internal static string NCJ {
            get {
                return ResourceManager.GetString("NCJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for player input before resuming script.
        /// </summary>
        internal static string NOD {
            get {
                return ResourceManager.GetString("NOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints the value [4a5b34+W*4] to the message box. Use 0000 to print the last used W from compatible commands (eg AM+).
        /// </summary>
        internal static string NUM {
            get {
                return ResourceManager.GetString("NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock player controls and freeze game action.
        /// </summary>
        internal static string PRI {
            get {
                return ResourceManager.GetString("PRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set teleporter slot W to event X. Selecting slot W while using the teleporter menu will jump to event X.
        /// </summary>
        internal static string PSPlus {
            get {
                return ResourceManager.GetString("PSPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shake the screen for W ticks.
        /// </summary>
        internal static string QUA {
            get {
                return ResourceManager.GetString("QUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume the song last played.
        /// </summary>
        internal static string RMU {
            get {
                return ResourceManager.GetString("RMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantly display text. Use before a &lt;MSG/2/3; works until &lt;END. Same command as &lt;CAT.
        /// </summary>
        internal static string SAT {
            get {
                return ResourceManager.GetString("SAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show illustration W (during credits).
        /// </summary>
        internal static string SIL {
            get {
                return ResourceManager.GetString("SIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to event X if skipflag W is set.
        /// </summary>
        internal static string SKJ {
            get {
                return ResourceManager.GetString("SKJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset skipflag W.
        /// </summary>
        internal static string SKMinus {
            get {
                return ResourceManager.GetString("SKMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set skipflag W.
        /// </summary>
        internal static string SKPlus {
            get {
                return ResourceManager.GetString("SKPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the teleporter menu.
        /// </summary>
        internal static string SLP {
            get {
                return ResourceManager.GetString("SLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the PC.
        /// </summary>
        internal static string SMC {
            get {
                return ResourceManager.GetString("SMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract 1 from the tile type at coordinates W:X. Does not create smoke.
        /// </summary>
        internal static string SMP {
            get {
                return ResourceManager.GetString("SMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an entity of type W at coordinates X:Y with direction Z.
        /// </summary>
        internal static string SNP {
            get {
                return ResourceManager.GetString("SNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound effect W.
        /// </summary>
        internal static string SOU {
            get {
                return ResourceManager.GetString("SOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the propeller sound.
        /// </summary>
        internal static string SPS {
            get {
                return ResourceManager.GetString("SPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the stream sound with volume W.
        /// </summary>
        internal static string SSS {
            get {
                return ResourceManager.GetString("SSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves current time to 290.rec.
        /// </summary>
        internal static string STC {
            get {
                return ResourceManager.GetString("STC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves current game.
        /// </summary>
        internal static string SVP {
            get {
                return ResourceManager.GetString("SVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade weapon W for weapon X and set max ammo to Y. Use 0000 to keep the same amount of ammo.
        /// </summary>
        internal static string TAM {
            get {
                return ResourceManager.GetString("TAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel to map W, run event X, and move the PC to coordinates Y:Z.
        /// </summary>
        internal static string TRA {
            get {
                return ResourceManager.GetString("TRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantly display text. Use after a &lt;MSG/2/3; works until another &lt;MSG/2/3 or an &lt;END.
        /// </summary>
        internal static string TUR {
            get {
                return ResourceManager.GetString("TUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set character movement type. Use 0000 for normal, 0001 for zero-G and 0002 to disallow movement..
        /// </summary>
        internal static string UNI {
            get {
                return ResourceManager.GetString("UNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to event X if movement is of type W (0000 for normal, 0001 for zero-G).
        /// </summary>
        internal static string UNJ {
            get {
                return ResourceManager.GetString("UNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause script for W ticks.
        /// </summary>
        internal static string WAI {
            get {
                return ResourceManager.GetString("WAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause script until character is on ground.
        /// </summary>
        internal static string WAS {
            get {
                return ResourceManager.GetString("WAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the island falling in manner W. Use 0000 to have it crash and 0001 to have it stop midway.
        /// </summary>
        internal static string XX1 {
            get {
                return ResourceManager.GetString("XX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt Yes/No; jump to event W if No is selected.
        /// </summary>
        internal static string YNJ {
            get {
                return ResourceManager.GetString("YNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets all weapon energy to zero.
        /// </summary>
        internal static string ZAM {
            get {
                return ResourceManager.GetString("ZAM", resourceCulture);
            }
        }
    }
}
