version: 1.0.{build}
skip_tags: true
configuration: Release
clone_folder: c:\projects\CaveStoryEditor
clone_script:
- cmd: >-
    git clone https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%/../

    git clone https://github.com/Brayconn/CaveStoryModdingFramework.git

    git clone https://github.com/Brayconn/PixelModdingFramework.git

    git clone https://github.com/Brayconn/PETools.git
before_build:
- cmd: >-
    nuget restore %APPVEYOR_BUILD_FOLDER%/TheKingsTable.sln

    dotnet restore %APPVEYOR_BUILD_FOLDER%
build:
  verbosity: minimal
after_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%/TheKingsTable/bin/%CONFIGURATION%/%PLATFORM%/

    7z a %CONFIGURATION%.zip *.exe *.dll *.png

    appveyor PushArtifact %CONFIGURATION%.zip