//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveStoryEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Keybinds : global::System.Configuration.ApplicationSettingsBase {
        
        private static Keybinds defaultInstance = ((Keybinds)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Keybinds())));
        
        public static Keybinds Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                    <KeybindCollection xmlns:xsi=\"http://www.w3.org/2001/XMLSch" +
            "ema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n                   " +
            "     <Keybinds>\r\n                            <Keybind>\r\n                        " +
            "        <Input>\r\n                                    <Shift>false</Shift>\r\n     " +
            "                               <Control>false</Control>\r\n                       " +
            "             <Alt>false</Alt>\r\n                                    <KeyValue>Oem" +
            "plus</KeyValue>\r\n                                </Input>\r\n                     " +
            "           <Action>ZoomIn</Action>\r\n                            </Keybind>\r\n    " +
            "                        <Keybind>\r\n                                <Input>\r\n    " +
            "                                <Shift>false</Shift>\r\n                          " +
            "          <Control>false</Control>\r\n                                    <Alt>fal" +
            "se</Alt>\r\n                                    <KeyValue>Add</KeyValue>\r\n        " +
            "                        </Input>\r\n                                <Action>ZoomIn" +
            "</Action>\r\n                            </Keybind>\r\n                            <" +
            "Keybind>\r\n                                <Input>\r\n                             " +
            "       <Shift>false</Shift>\r\n                                    <Control>false<" +
            "/Control>\r\n                                    <Alt>false</Alt>\r\n               " +
            "                     <KeyValue>OemMinus</KeyValue>\r\n                            " +
            "    </Input>\r\n                                <Action>ZoomOut</Action>\r\n        " +
            "                    </Keybind>\r\n                            <Keybind>\r\n         " +
            "                       <Input>\r\n                                    <Shift>false" +
            "</Shift>\r\n                                    <Control>false</Control>\r\n        " +
            "                            <Alt>false</Alt>\r\n                                  " +
            "  <KeyValue>Subtract</KeyValue>\r\n                                </Input>\r\n     " +
            "                           <Action>ZoomOut</Action>\r\n                           " +
            " </Keybind>\r\n                            <Keybind>\r\n                            " +
            "    <Input>\r\n                                    <Shift>false</Shift>\r\n         " +
            "                           <Control>false</Control>\r\n                           " +
            "         <Alt>false</Alt>\r\n                                    <KeyValue>P</KeyV" +
            "alue>\r\n                                </Input>\r\n                               " +
            " <Action>PickTile</Action>\r\n                            </Keybind>\r\n            " +
            "                <Keybind>\r\n                                <Input>\r\n            " +
            "                        <Shift>false</Shift>\r\n                                  " +
            "  <Control>false</Control>\r\n                                    <Alt>false</Alt>" +
            "\r\n                                    <KeyValue>Insert</KeyValue>\r\n             " +
            "                   </Input>\r\n                                <Action>InsertEntit" +
            "y</Action>\r\n                            </Keybind>\r\n                            " +
            "<Keybind>\r\n                                <Input>\r\n                            " +
            "        <Shift>false</Shift>\r\n                                    <Control>false" +
            "</Control>\r\n                                    <Alt>false</Alt>\r\n              " +
            "                      <KeyValue>I</KeyValue>\r\n                                </" +
            "Input>\r\n                                <Action>InsertEntity</Action>\r\n         " +
            "                   </Keybind>\r\n                            <Keybind>\r\n          " +
            "                      <Input>\r\n                                    <Shift>false<" +
            "/Shift>\r\n                                    <Control>false</Control>\r\n         " +
            "                           <Alt>false</Alt>\r\n                                   " +
            " <KeyValue>Delete</KeyValue>\r\n                                </Input>\r\n        " +
            "                        <Action>DeleteEntities</Action>\r\n                       " +
            "     </Keybind>\r\n                            <Keybind>\r\n                        " +
            "        <Input>\r\n                                    <Shift>false</Shift>\r\n     " +
            "                               <Control>true</Control>\r\n                        " +
            "            <Alt>false</Alt>\r\n                                    <KeyValue>C</K" +
            "eyValue>\r\n                                </Input>\r\n                            " +
            "    <Action>Copy</Action>\r\n                            </Keybind>\r\n             " +
            "               <Keybind>\r\n                                <Input>\r\n             " +
            "                       <Shift>false</Shift>\r\n                                   " +
            " <Control>true</Control>\r\n                                    <Alt>false</Alt>\r\n" +
            "                                    <KeyValue>V</KeyValue>\r\n                    " +
            "            </Input>\r\n                                <Action>Paste</Action>\r\n  " +
            "                          </Keybind>\r\n                            <Keybind>\r\n   " +
            "                             <Input>\r\n                                    <Shift" +
            ">false</Shift>\r\n                                    <Control>true</Control>\r\n   " +
            "                                 <Alt>false</Alt>\r\n                             " +
            "       <KeyValue>Z</KeyValue>\r\n                                </Input>\r\n       " +
            "                         <Action>Undo</Action>\r\n                            </Ke" +
            "ybind>\r\n                            <Keybind>\r\n                                <" +
            "Input>\r\n                                    <Shift>true</Shift>\r\n               " +
            "                     <Control>true</Control>\r\n                                  " +
            "  <Alt>false</Alt>\r\n                                    <KeyValue>Z</KeyValue>\r\n" +
            "                                </Input>\r\n                                <Actio" +
            "n>Redo</Action>\r\n                            </Keybind>\r\n                       " +
            "     <Keybind>\r\n                                <Input>\r\n                       " +
            "             <Shift>false</Shift>\r\n                                    <Control>" +
            "true</Control>\r\n                                    <Alt>false</Alt>\r\n          " +
            "                          <KeyValue>Y</KeyValue>\r\n                              " +
            "  </Input>\r\n                                <Action>Redo</Action>\r\n             " +
            "               </Keybind>\r\n                            <Keybind>\r\n              " +
            "                  <Input>\r\n                                    <Shift>false</Shi" +
            "ft>\r\n                                    <Control>true</Control>\r\n              " +
            "                      <Alt>false</Alt>\r\n                                    <Key" +
            "Value>S</KeyValue>\r\n                                </Input>\r\n                  " +
            "              <Action>Save</Action>\r\n                            </Keybind>\r\n   " +
            "                     </Keybinds>\r\n                    </KeybindCollection>\r\n\r\n  " +
            "              ")]
        public global::WinFormsKeybinds.KeybindCollection StageEditor {
            get {
                return ((global::WinFormsKeybinds.KeybindCollection)(this["StageEditor"]));
            }
        }
    }
}
