//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveStoryModdingFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BackgroundTypeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackgroundTypeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaveStoryModdingFramework.Lists.BackgroundTypeNames", typeof(BackgroundTypeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed To Camera.
        /// </summary>
        internal static string FixedToCamera {
            get {
                return ResourceManager.GetString("FixedToCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed To Foreground.
        /// </summary>
        internal static string FixedToForeground {
            get {
                return ResourceManager.GetString("FixedToForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Slowly.
        /// </summary>
        internal static string FollowSlowly {
            get {
                return ResourceManager.GetString("FollowSlowly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Draw.
        /// </summary>
        internal static string NoDraw {
            get {
                return ResourceManager.GetString("NoDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallax.
        /// </summary>
        internal static string Parallax {
            get {
                return ResourceManager.GetString("Parallax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallax (Items).
        /// </summary>
        internal static string ParallaxItems {
            get {
                return ResourceManager.GetString("ParallaxItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll (Items).
        /// </summary>
        internal static string ScrollItems {
            get {
                return ResourceManager.GetString("ScrollItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
    }
}
